// Education content — single source of truth for every concept the dashboard
// shows. Keyed by a stable `key`; UI components look entries up by that key.
//
// Schema per entry:
//   key, title, short, what, how, read[ {when, meaning, tone} ], why,
//   analogy, example, level (basic|intermediate|advanced), category
//   hi: { short, what, how, why, analogy, example, read[{meaning}] }  ← Hindi
//
// Hindi (`hi`) keeps technical terms in English ("Hinglish"). Use localize()
// to resolve fields for the active language (falls back to English).
//
// `tone` is one of: bullish | bearish | neutral  (drives color).

export const CATEGORIES = [
  "Basics",
  "Sentiment",
  "OI Patterns",
  "Levels",
  "Volatility",
  "Gamma",
  "Greeks",
  "Engine",
  "Strategy",
];

// Hindi display names for category headers/filters.
export const CATEGORY_LABELS = {
  Basics: "बेसिक्स (Basics)",
  Sentiment: "सेंटिमेंट (Sentiment)",
  "OI Patterns": "OI पैटर्न",
  Levels: "लेवल्स (Levels)",
  Volatility: "वोलैटिलिटी (Volatility)",
  Gamma: "गामा (Gamma)",
  Greeks: "ग्रीक्स (Greeks)",
  Engine: "इंजन (Engine)",
  Strategy: "स्ट्रैटेजी (Strategy)",
};

export function categoryLabel(cat, lang) {
  return lang === "hi" ? CATEGORY_LABELS[cat] || cat : cat;
}

export const GLOSSARY = {
  // ── Basics ────────────────────────────────────────────────────────────
  spot: {
    key: "spot",
    title: "Spot Price",
    short: "The live price of the underlying (e.g. NIFTY) right now.",
    what: "The current traded price of the index or stock the options are based on.",
    how: "NSE CSVs don't include spot, so we estimate it from the ATM strike using put-call parity: spot ≈ strike + call_LTP − put_LTP.",
    read: [],
    why: "Everything — support, resistance, moneyness, expected move — is measured relative to spot. It's your anchor.",
    analogy: "The 'you are here' dot on a map. Levels above are resistance, below are support.",
    example: "If spot is 23,450, a 23,700 call is out-of-the-money and a 23,250 put is out-of-the-money.",
    level: "basic",
    category: "Basics",
    hi: {
      short: "Underlying (जैसे NIFTY) की अभी की live price.",
      what: "जिस index या stock पर options बने हैं, उसका current traded price.",
      how: "NSE CSV में spot नहीं होता, इसलिए हम ATM strike से put-call parity द्वारा estimate करते हैं: spot ≈ strike + call_LTP − put_LTP.",
      why: "Support, resistance, moneyness, expected move — सब कुछ spot के मुकाबले नापा जाता है। यह आपका anchor है।",
      analogy: "नक़्शे पर 'आप यहाँ हैं' वाला बिंदु। ऊपर के levels resistance, नीचे के support.",
      example: "Spot 23,450 है तो 23,700 call out-of-the-money है और 23,250 put भी out-of-the-money है।",
    },
  },
  atm: {
    key: "atm",
    title: "ATM — At The Money",
    short: "The strike closest to the current spot price.",
    what: "The strike where the call and put prices are nearly equal — i.e. closest to spot.",
    how: "We pick the strike where |call_LTP − put_LTP| is smallest.",
    read: [],
    why: "ATM options have the most time value and the highest gamma, so the ATM zone is where the action and the clearest signals are.",
    analogy: "The coin balanced on its edge — could fall either way.",
    example: "Spot 23,450 → ATM strike is 23,450 (or the nearest listed strike).",
    level: "basic",
    category: "Basics",
    hi: {
      short: "Current spot price के सबसे पास वाला strike.",
      what: "वह strike जहाँ call और put की price लगभग बराबर हो — यानी spot के सबसे करीब।",
      how: "हम वह strike चुनते हैं जहाँ |call_LTP − put_LTP| सबसे कम हो।",
      why: "ATM options में सबसे ज़्यादा time value और highest gamma होता है, इसलिए असली action और सबसे साफ़ signals ATM zone में मिलते हैं।",
      analogy: "किनारे पर खड़ा सिक्का — किसी भी तरफ़ गिर सकता है।",
      example: "Spot 23,450 → ATM strike 23,450 (या सबसे पास वाला listed strike)।",
    },
  },
  oi: {
    key: "oi",
    title: "OI — Open Interest",
    short: "Number of option contracts currently open (not yet closed).",
    what: "The total count of outstanding contracts at a strike — positions that are still live.",
    how: "Reported per strike by the exchange. We show it in lakhs (1 L = 100,000).",
    read: [
      { when: "Rising OI", meaning: "New money entering — the move/level is being backed", tone: "neutral" },
      { when: "Falling OI", meaning: "Positions closing — conviction leaving that level", tone: "neutral" },
    ],
    why: "OI shows where traders have committed money. Big OI at a strike = a level many participants care about → it acts as support or resistance.",
    analogy: "Like the number of bets placed on a horse — more bets, more interest, more significance.",
    example: "A strike with 40 L call OI is a wall many call sellers are defending → resistance.",
    level: "basic",
    category: "Basics",
    hi: {
      short: "अभी open (बंद न हुए) option contracts की संख्या।",
      what: "किसी strike पर बचे हुए कुल contracts — वे positions जो अभी live हैं।",
      how: "Exchange हर strike के लिए बताता है। हम इसे lakhs में दिखाते हैं (1 L = 1,00,000)।",
      read: [
        { meaning: "नया पैसा आ रहा है — उस move/level को support मिल रहा है" },
        { meaning: "Positions बंद हो रहे हैं — उस level से conviction हट रहा है" },
      ],
      why: "OI बताता है कि traders ने कहाँ पैसा लगाया है। किसी strike पर बड़ा OI = ऐसा level जिसकी कई लोग परवाह करते हैं → वह support या resistance बनता है।",
      analogy: "जैसे किसी घोड़े पर लगे दांव की संख्या — जितने ज़्यादा दांव, उतनी ज़्यादा अहमियत।",
      example: "40 L call OI वाला strike एक wall है जिसे कई call sellers defend कर रहे हैं → resistance.",
    },
  },
  volume: {
    key: "volume",
    title: "Volume",
    short: "How many contracts traded today (activity, not positions).",
    what: "The number of contracts bought/sold during the session — a measure of current activity.",
    how: "Reported per strike. Unlike OI, it resets each day.",
    read: [],
    why: "High volume confirms interest *right now*. A level with both high OI and high volume is actively being fought over.",
    analogy: "OI is how many people are in the stadium; volume is how loud they're cheering today.",
    example: "The 'Battlefield' strike is simply the strike with the highest call+put volume.",
    level: "basic",
    category: "Basics",
    hi: {
      short: "आज कितने contracts trade हुए (activity, positions नहीं)।",
      what: "session के दौरान खरीदे/बेचे गए contracts की संख्या — मौजूदा activity का माप।",
      how: "हर strike के लिए बताया जाता है। OI के उलट, यह हर दिन reset होता है।",
      why: "ज़्यादा volume *अभी* की दिलचस्पी confirm करता है। जिस level पर OI और volume दोनों ज़्यादा हों, वहाँ active लड़ाई चल रही है।",
      analogy: "OI = stadium में कितने लोग हैं; volume = आज वे कितनी ज़ोर से चिल्ला रहे हैं।",
      example: "'Battlefield' strike बस वह strike है जहाँ call+put volume सबसे ज़्यादा है।",
    },
  },
  ltp: {
    key: "ltp",
    title: "LTP — Last Traded Price",
    short: "The premium (price) the option last traded at.",
    what: "The most recent price paid for that specific call or put.",
    how: "Reported per strike for both calls and puts.",
    read: [],
    why: "Premiums tell you what the market charges for a bet, and the ATM call+put together reveal the market's expected move.",
    analogy: "The ticket price for a bet on direction.",
    example: "ATM call LTP 90 + ATM put LTP 85 = market expects roughly a ±175-point move by expiry.",
    level: "basic",
    category: "Basics",
    hi: {
      short: "Option जिस premium (price) पर आख़िरी बार trade हुआ।",
      what: "उस ख़ास call या put के लिए दी गई सबसे हाल की price.",
      how: "हर strike के लिए calls और puts दोनों का बताया जाता है।",
      why: "Premium बताता है कि market किसी दांव के लिए कितना charge कर रहा है, और ATM call+put मिलकर market का expected move बताते हैं।",
      analogy: "Direction पर दांव लगाने की टिकट की कीमत।",
      example: "ATM call LTP 90 + ATM put LTP 85 = market expiry तक लगभग ±175 point move की उम्मीद कर रहा है।",
    },
  },
  dte: {
    key: "dte",
    title: "DTE — Days To Expiry",
    short: "How many days until the options expire.",
    what: "The number of calendar days remaining until the option contracts settle.",
    how: "Computed from the expiry date you enter (defaults to 7 if none).",
    read: [
      { when: "≤ 3 days", meaning: "Theta (time decay) dominates — buying options is dangerous", tone: "bearish" },
      { when: "4–7 days", meaning: "Max Pain / pinning effects strengthen", tone: "neutral" },
      { when: "> 7 days", meaning: "More room for direction to play out", tone: "neutral" },
    ],
    why: "Time is fuel for option buyers and a friend to sellers. Near expiry, prices get pulled toward high-OI strikes (pinning) and bought options bleed value fast.",
    analogy: "An ice cube melting — the closer to expiry, the faster an option's time value disappears.",
    example: "With 2 DTE the app refuses directional buying: 'NO TRADE — theta kills buyers.'",
    level: "basic",
    category: "Basics",
    hi: {
      short: "Options की expiry में कितने दिन बचे हैं।",
      what: "Option contracts के settle होने में बचे calendar दिनों की संख्या।",
      how: "आपके डाले expiry date से निकाला जाता है (न डालें तो default 7)।",
      read: [
        { meaning: "Theta (time decay) हावी — options खरीदना ख़तरनाक" },
        { meaning: "Max Pain / pinning का असर बढ़ता है" },
        { meaning: "Direction को चलने की ज़्यादा जगह" },
      ],
      why: "Time, option buyers का ईंधन है और sellers का दोस्त। Expiry के पास price high-OI strikes की तरफ़ खिंचती है (pinning) और खरीदे options की value तेज़ी से घटती है।",
      analogy: "पिघलता बर्फ़ का टुकड़ा — expiry जितनी पास, time value उतनी तेज़ी से ग़ायब।",
      example: "2 DTE पर app directional buying से मना करता है: 'NO TRADE — theta kills buyers.'",
    },
  },

  // ── Sentiment ─────────────────────────────────────────────────────────
  pcr: {
    key: "pcr",
    title: "PCR (OI) — Put/Call Ratio",
    short: "Puts open vs calls open. A crowd-sentiment and support/resistance gauge.",
    what: "Total PUT open interest divided by total CALL open interest across the chain.",
    how: "Σ all put OI ÷ Σ all call OI.",
    read: [
      { when: "< 0.7", meaning: "Far more calls — crowd over-bullish, often a bearish contrarian signal", tone: "bearish" },
      { when: "0.7–0.9", meaning: "Call-heavy — mild bearish lean", tone: "bearish" },
      { when: "0.9–1.1", meaning: "Balanced — neutral", tone: "neutral" },
      { when: "1.1–1.4", meaning: "Put writers active below — bullish support building", tone: "bullish" },
      { when: "> 1.4", meaning: "Heavy put writing — strong bullish support", tone: "bullish" },
    ],
    why: "Option writers (often well-capitalised 'smart money') sell the side they expect to expire worthless. Lots of put writing = they expect price to hold up → bullish. The ratio captures this balance.",
    analogy: "Counting umbrellas vs sunglasses sold at a stall — it tells you what the crowd expects the weather to do.",
    example: "PCR climbs 0.9 → 1.3: traders are writing puts below price, building a floor → bullish.",
    level: "basic",
    category: "Sentiment",
    hi: {
      short: "खुले puts बनाम खुले calls. भीड़ का sentiment और support/resistance का gauge.",
      what: "पूरी chain का कुल PUT open interest ÷ कुल CALL open interest.",
      how: "Σ सभी put OI ÷ Σ सभी call OI.",
      read: [
        { meaning: "बहुत ज़्यादा calls — भीड़ over-bullish, अक्सर bearish contrarian signal" },
        { meaning: "Call-heavy — हल्का bearish झुकाव" },
        { meaning: "Balanced — neutral" },
        { meaning: "नीचे put writers active — bullish support बन रहा है" },
        { meaning: "भारी put writing — मज़बूत bullish support" },
      ],
      why: "Option writers (अक्सर बड़े पैसे वाले 'smart money') वही side बेचते हैं जो उन्हें worthless expire होती लगती है। ज़्यादा put writing = उन्हें price टिकी रहने की उम्मीद → bullish.",
      analogy: "किसी दुकान पर बिके छातों बनाम धूप के चश्मों की गिनती — बता देती है कि भीड़ मौसम को लेकर क्या सोच रही है।",
      example: "PCR 0.9 → 1.3 हुआ और spot 23,400 पर रुका: traders 23,300 के नीचे puts लिख रहे हैं → floor बन रहा है → bullish.",
    },
  },
  volume_ratio: {
    key: "volume_ratio",
    title: "PCR (Volume)",
    short: "Put vs call ratio using today's traded volume instead of OI.",
    what: "Total PUT volume ÷ total CALL volume — the intraday version of PCR.",
    how: "Σ put volume ÷ Σ call volume.",
    read: [
      { when: "< 0.8", meaning: "Calls being traded harder — bearish intraday tilt", tone: "bearish" },
      { when: "0.8–1.2", meaning: "Balanced activity", tone: "neutral" },
      { when: "> 1.2", meaning: "Puts being traded harder — bullish intraday tilt", tone: "bullish" },
    ],
    why: "OI-based PCR is slow (positions build over days); volume PCR reacts to *today's* flow, so it's an earlier hint of a shift in sentiment.",
    analogy: "OI-PCR is the season standings; volume-PCR is today's score.",
    example: "OI-PCR flat at 1.0 but volume-PCR spikes to 1.4 → fresh bullish flow starting today.",
    level: "intermediate",
    category: "Sentiment",
    hi: {
      short: "OI की जगह आज के traded volume से बनाया put बनाम call ratio.",
      what: "कुल PUT volume ÷ कुल CALL volume — PCR का intraday version.",
      how: "Σ put volume ÷ Σ call volume.",
      read: [
        { meaning: "Calls ज़्यादा trade हो रहे — bearish intraday झुकाव" },
        { meaning: "Balanced activity" },
        { meaning: "Puts ज़्यादा trade हो रहे — bullish intraday झुकाव" },
      ],
      why: "OI वाला PCR धीमा है (positions कई दिनों में बनते हैं); volume PCR *आज* के flow पर react करता है, इसलिए sentiment बदलने का पहले संकेत देता है।",
      analogy: "OI-PCR = season की standings; volume-PCR = आज का score.",
      example: "OI-PCR 1.0 पर flat लेकिन volume-PCR 1.4 तक उछला → आज ही fresh bullish flow शुरू।",
    },
  },
  max_pain: {
    key: "max_pain",
    title: "Max Pain",
    short: "The strike where option buyers lose the most — price tends to gravitate here near expiry.",
    what: "The strike at which the total value of in-the-money options (the payout option writers owe) is lowest.",
    how: "For each candidate strike, sum what all calls and puts would pay out; the one with the smallest total is Max Pain.",
    read: [
      { when: "Spot far ABOVE Max Pain", meaning: "Downward pull toward Max Pain", tone: "bearish" },
      { when: "Spot near Max Pain", meaning: "Likely to stay / pin here", tone: "neutral" },
      { when: "Spot far BELOW Max Pain", meaning: "Upward pull toward Max Pain", tone: "bullish" },
    ],
    why: "Option sellers (who profit when options expire worthless) have an incentive — and often the firepower — to nudge price toward the strike where buyers lose most. The effect is strongest in the last few days.",
    analogy: "A magnet under the table that pulls the marble (price) toward a certain spot as expiry nears.",
    example: "Spot 23,450, Max Pain 23,500, expiry tomorrow → mild upward pull toward 23,500.",
    level: "basic",
    category: "Sentiment",
    hi: {
      short: "वह strike जहाँ option buyers सबसे ज़्यादा हारते हैं — expiry के पास price यहीं खिंचती है।",
      what: "वह strike जहाँ in-the-money options की कुल value (जो writers को चुकानी है) सबसे कम हो।",
      how: "हर strike के लिए जोड़ो कि सारे calls और puts कितना payout देंगे; जिसका कुल सबसे कम वही Max Pain.",
      read: [
        { meaning: "Max Pain की तरफ़ नीचे का खिंचाव" },
        { meaning: "यहीं टिकने / pin होने की संभावना" },
        { meaning: "Max Pain की तरफ़ ऊपर का खिंचाव" },
      ],
      why: "Option sellers (जो options worthless expire होने पर कमाते हैं) के पास price को उस strike की तरफ़ धकेलने का फ़ायदा — और अक्सर ताक़त — होती है जहाँ buyers सबसे ज़्यादा हारें। यह असर आख़िरी कुछ दिनों में सबसे तेज़।",
      analogy: "मेज़ के नीचे रखा चुम्बक जो expiry पास आते ही कंचे (price) को किसी जगह खींचता है।",
      example: "Spot 23,450, Max Pain 23,500, कल expiry → 23,500 की तरफ़ हल्का ऊपर का खिंचाव।",
    },
  },
  battlefield: {
    key: "battlefield",
    title: "Battlefield Strike",
    short: "The strike with the highest combined call+put volume today.",
    what: "Where the most contracts are changing hands — the day's most contested price.",
    how: "The strike that maximises (call volume + put volume).",
    read: [],
    why: "It marks the price level bulls and bears are actively fighting over right now — often the pivot for the session.",
    analogy: "The hill both armies are charging at — whoever wins it usually wins the day.",
    example: "Battlefield at 23,500 with 107 L volume → that's today's key decision level.",
    level: "intermediate",
    category: "Sentiment",
    hi: {
      short: "वह strike जहाँ आज सबसे ज़्यादा call+put volume मिलाकर है।",
      what: "जहाँ सबसे ज़्यादा contracts हाथ बदल रहे हैं — दिन का सबसे विवादित price.",
      how: "वह strike जहाँ (call volume + put volume) सबसे ज़्यादा हो।",
      why: "यह वह level दिखाता है जिस पर अभी bulls और bears active लड़ रहे हैं — अक्सर session का pivot.",
      analogy: "वह पहाड़ी जिस पर दोनों सेनाएँ हमला कर रही हैं — जो जीते वही दिन जीतता है।",
      example: "23,500 पर Battlefield, 107 L volume → आज का key decision level वही है।",
    },
  },

  // ── OI Patterns ───────────────────────────────────────────────────────
  oi_pattern: {
    key: "oi_pattern",
    title: "OI Build-up Pattern",
    short: "Combines change in OI with price change to reveal what traders are doing.",
    what: "A classification of each strike based on whether OI and price rose or fell together.",
    how: "Cross OI direction with price direction → one of four build-up types (see below).",
    read: [
      { when: "Long Build (OI↑ Price↑)", meaning: "New buyers — bullish conviction", tone: "bullish" },
      { when: "Short Build (OI↑ Price↓)", meaning: "New sellers — bearish (on calls = ceiling forming)", tone: "bearish" },
      { when: "Short Cover (OI↓ Price↑)", meaning: "Sellers exiting — bullish relief", tone: "bullish" },
      { when: "Long Unwind (OI↓ Price↓)", meaning: "Buyers exiting — bearish", tone: "bearish" },
    ],
    why: "Price alone is ambiguous; pairing it with OI tells you whether a move is backed by fresh money (sustainable) or just position-closing (fragile).",
    analogy: "Knowing not just that a crowd moved, but whether new people joined or others left.",
    example: "Call OI rising while call price falls = Short Build → writers capping that strike → resistance.",
    level: "intermediate",
    category: "OI Patterns",
    hi: {
      short: "OI के change को price के change के साथ जोड़कर बताता है कि traders क्या कर रहे हैं।",
      what: "हर strike की पहचान कि OI और price साथ में बढ़े या घटे।",
      how: "OI की दिशा को price की दिशा से मिलाओ → चार build-up types में से एक (नीचे देखें)।",
      read: [
        { meaning: "नए buyers — bullish conviction" },
        { meaning: "नए sellers — bearish (calls पर = ceiling बन रहा)" },
        { meaning: "Sellers बाहर निकल रहे — bullish राहत" },
        { meaning: "Buyers बाहर निकल रहे — bearish" },
      ],
      why: "अकेली price धोखा दे सकती है; OI के साथ जोड़ने से पता चलता है कि move को fresh पैसा support कर रहा है (टिकाऊ) या बस position-closing है (कमज़ोर)।",
      analogy: "सिर्फ़ यह नहीं कि भीड़ हिली, बल्कि यह कि नए लोग जुड़े या पुराने चले गए।",
      example: "Call OI बढ़ रहा और call price गिर रहा = Short Build → writers उस strike को cap कर रहे → resistance.",
    },
  },
  call_writing: {
    key: "call_writing",
    title: "Call Writing Intensity",
    short: "Fresh call selling above spot — builds a ceiling (bearish).",
    what: "How much new call OI is being written (sold) in the ATM-to-ATM+300 zone.",
    how: "Sum of positive call OI changes where the call price also fell (fresh writing), normalised by total OI.",
    read: [
      { when: "High", meaning: "Strong ceiling forming above — bearish/capped", tone: "bearish" },
      { when: "Low", meaning: "Little resistance being built", tone: "neutral" },
    ],
    why: "Call writers profit if price stays below their strike, so heavy call writing marks where 'smart money' expects price to stall → resistance.",
    analogy: "Builders putting a roof on the house — price struggles to push through it.",
    example: "Big fresh call OI at 23,700 → sellers defending it → strong resistance there.",
    level: "intermediate",
    category: "OI Patterns",
    hi: {
      short: "Spot के ऊपर fresh call selling — ceiling बनाती है (bearish)।",
      what: "ATM-से-ATM+300 zone में कितना नया call OI लिखा (बेचा) जा रहा है।",
      how: "जहाँ call price भी गिरी हो (fresh writing) वहाँ के positive call OI changes का जोड़, total OI से normalise करके।",
      read: [
        { meaning: "ऊपर मज़बूत ceiling बन रहा — bearish/capped" },
        { meaning: "बहुत कम resistance बन रहा" },
      ],
      why: "Call writers तब कमाते हैं जब price उनके strike के नीचे रहे, इसलिए भारी call writing वहाँ दिखती है जहाँ 'smart money' price रुकने की उम्मीद करता है → resistance.",
      analogy: "मिस्त्री घर पर छत डाल रहे हों — price उसे तोड़कर ऊपर जाने में संघर्ष करती है।",
      example: "23,700 पर बड़ा fresh call OI → sellers उसे defend कर रहे → वहाँ मज़बूत resistance.",
    },
  },
  put_writing: {
    key: "put_writing",
    title: "Put Writing Intensity",
    short: "Fresh put selling below spot — builds a floor (bullish).",
    what: "How much new put OI is being written (sold) in the ATM-300-to-ATM zone.",
    how: "Sum of positive put OI changes where the put price also fell (fresh writing), normalised by total OI.",
    read: [
      { when: "High", meaning: "Strong floor forming below — bullish support", tone: "bullish" },
      { when: "Low", meaning: "Little support being built", tone: "neutral" },
    ],
    why: "Put writers profit if price stays above their strike, so heavy put writing marks where smart money expects price to hold → support.",
    analogy: "Builders laying a floor under the house — price tends to bounce off it.",
    example: "Big fresh put OI at 23,250 → sellers backing it → strong support there.",
    level: "intermediate",
    category: "OI Patterns",
    hi: {
      short: "Spot के नीचे fresh put selling — floor बनाती है (bullish)।",
      what: "ATM-300-से-ATM zone में कितना नया put OI लिखा (बेचा) जा रहा है।",
      how: "जहाँ put price भी गिरी हो (fresh writing) वहाँ के positive put OI changes का जोड़, total OI से normalise करके।",
      read: [
        { meaning: "नीचे मज़बूत floor बन रहा — bullish support" },
        { meaning: "बहुत कम support बन रहा" },
      ],
      why: "Put writers तब कमाते हैं जब price उनके strike के ऊपर रहे, इसलिए भारी put writing वहाँ दिखती है जहाँ smart money price टिकने की उम्मीद करता है → support.",
      analogy: "मिस्त्री घर के नीचे फ़र्श डाल रहे हों — price उससे टकराकर bounce करती है।",
      example: "23,250 पर बड़ा fresh put OI → sellers उसका साथ दे रहे → वहाँ मज़बूत support.",
    },
  },

  // ── Levels ────────────────────────────────────────────────────────────
  resistance: {
    key: "resistance",
    title: "Resistance (Call Walls)",
    short: "Strikes with heavy call OI above price — likely ceilings.",
    what: "Price levels where large call open interest can cap upside moves.",
    how: "Top strikes ranked by call OI, weighted by fresh OI change (fresh writing strengthens, unwinding weakens).",
    read: [
      { when: "VERY STRONG / STRONG", meaning: "Hard ceiling — expect price to stall or reverse", tone: "bearish" },
      { when: "Fresh", meaning: "Wall is being reinforced right now", tone: "bearish" },
      { when: "Weakening", meaning: "Wall is being dismantled — may break", tone: "bullish" },
    ],
    why: "Call sellers defend their strikes by hedging, which creates real selling pressure as price approaches — turning a high-OI strike into a ceiling.",
    analogy: "A ceiling in a room — you can jump toward it but usually bounce back down.",
    example: "23,700 with VERY STRONG fresh call OI → strong resistance; a close above it is a bullish breakout.",
    level: "basic",
    category: "Levels",
    hi: {
      short: "Price के ऊपर भारी call OI वाले strikes — संभावित ceilings.",
      what: "वे price levels जहाँ बड़ा call open interest ऊपर की move को cap कर सकता है।",
      how: "Call OI के हिसाब से top strikes, fresh OI change से weighted (fresh writing मज़बूत करती है, unwinding कमज़ोर)।",
      read: [
        { meaning: "सख़्त ceiling — price रुक या पलट सकती है" },
        { meaning: "Wall अभी मज़बूत हो रहा है" },
        { meaning: "Wall टूट रहा है — break हो सकता है" },
      ],
      why: "Call sellers hedging करके अपने strikes defend करते हैं, जिससे price पास आते ही असली selling pressure बनता है — high-OI strike को ceiling बना देता है।",
      analogy: "कमरे की छत — आप उछलकर उस तक जा सकते हैं पर आमतौर पर वापस नीचे आते हैं।",
      example: "23,700 पर VERY STRONG fresh call OI → मज़बूत resistance; उसके ऊपर close होना bullish breakout है।",
    },
  },
  support: {
    key: "support",
    title: "Support (Put Walls)",
    short: "Strikes with heavy put OI below price — likely floors.",
    what: "Price levels where large put open interest can cushion downside moves.",
    how: "Top strikes ranked by put OI, weighted by fresh OI change.",
    read: [
      { when: "VERY STRONG / STRONG", meaning: "Hard floor — expect price to bounce", tone: "bullish" },
      { when: "Fresh", meaning: "Floor being reinforced right now", tone: "bullish" },
      { when: "Weakening", meaning: "Floor being removed — may break down", tone: "bearish" },
    ],
    why: "Put sellers defend their strikes by hedging, creating buying support as price falls toward them — turning a high-OI strike into a floor.",
    analogy: "A floor under your feet — price can dip toward it but usually bounces.",
    example: "23,250 with STRONG put OI → support; a close below it is a bearish breakdown.",
    level: "basic",
    category: "Levels",
    hi: {
      short: "Price के नीचे भारी put OI वाले strikes — संभावित floors.",
      what: "वे price levels जहाँ बड़ा put open interest नीचे की move को सहारा दे सकता है।",
      how: "Put OI के हिसाब से top strikes, fresh OI change से weighted.",
      read: [
        { meaning: "सख़्त floor — price bounce कर सकती है" },
        { meaning: "Floor अभी मज़बूत हो रहा है" },
        { meaning: "Floor हट रहा है — breakdown हो सकता है" },
      ],
      why: "Put sellers hedging करके अपने strikes defend करते हैं, जिससे price नीचे आते ही buying support बनता है — high-OI strike को floor बना देता है।",
      analogy: "पैरों के नीचे फ़र्श — price उस तक गिर सकती है पर आमतौर पर bounce करती है।",
      example: "23,250 पर STRONG put OI → support; उसके नीचे close होना bearish breakdown है।",
    },
  },
  sr_zones: {
    key: "sr_zones",
    title: "Support/Resistance Zones",
    short: "Bands where several adjacent high-OI strikes cluster together.",
    what: "Real S/R is usually a *range*, not one exact strike. Zones merge neighbouring strong strikes into a band.",
    how: "Adjacent strikes whose OI exceeds the chain average are clustered; the combined band and total OI are shown.",
    read: [],
    why: "Trading a single number is fragile; a zone tells you the area price will likely react in, which is more realistic and robust.",
    analogy: "A speed-bump zone rather than a single painted line.",
    example: "23,400–23,500 resistance zone (combined 60 L) is more reliable than betting on exactly 23,450.",
    level: "intermediate",
    category: "Levels",
    hi: {
      short: "वे bands जहाँ कई पास-पास के high-OI strikes एक साथ इकट्ठा होते हैं।",
      what: "असली S/R आमतौर पर एक *range* होती है, एक exact strike नहीं। Zones पड़ोसी मज़बूत strikes को एक band में जोड़ देते हैं।",
      how: "जिन पास-पास के strikes का OI chain के average से ज़्यादा हो उन्हें cluster करते हैं; मिला हुआ band और total OI दिखाते हैं।",
      why: "एक ही number पर trade करना कमज़ोर है; zone बताता है कि price किस इलाक़े में react करेगी, जो ज़्यादा realistic और मज़बूत है।",
      analogy: "एक खींची लकीर की जगह एक speed-bump इलाक़ा।",
      example: "23,400–23,500 resistance zone (मिलाकर 60 L) ठीक 23,450 पर दांव लगाने से ज़्यादा भरोसेमंद है।",
    },
  },
  strength: {
    key: "strength",
    title: "Wall Strength",
    short: "How dominant a level is, by its share of total side OI.",
    what: "A label (VERY STRONG → WEAK) based on what fraction of one side's total OI sits at that strike.",
    how: ">15% = VERY STRONG, >10% = STRONG, >5% = MODERATE, else WEAK.",
    read: [],
    why: "A level holding a big slice of all OI is one many traders defend, so it's more likely to actually hold.",
    analogy: "The thickness of a wall — thicker walls are harder to break.",
    example: "A strike with 18% of all call OI = VERY STRONG resistance.",
    level: "basic",
    category: "Levels",
    hi: {
      short: "कोई level कितना दमदार है, उस side के कुल OI में उसके हिस्से से।",
      what: "एक label (VERY STRONG → WEAK) इस आधार पर कि उस side के कुल OI का कितना हिस्सा उस strike पर है।",
      how: ">15% = VERY STRONG, >10% = STRONG, >5% = MODERATE, वरना WEAK.",
      why: "जो level पूरे OI का बड़ा हिस्सा रखता है उसे कई traders defend करते हैं, इसलिए उसके सच में टिकने की संभावना ज़्यादा।",
      analogy: "दीवार की मोटाई — मोटी दीवारें तोड़ना मुश्किल।",
      example: "जिस strike पर सारे call OI का 18% हो = VERY STRONG resistance.",
    },
  },

  // ── Volatility ────────────────────────────────────────────────────────
  iv: {
    key: "iv",
    title: "IV — Implied Volatility",
    short: "The market's expectation of how much price will move (priced into options).",
    what: "The volatility implied by current option prices — higher IV means pricier options and bigger expected swings.",
    how: "Back-solved from option prices. We show ATM and OTM IV across the chain.",
    read: [
      { when: "High IV", meaning: "Big moves expected — options expensive — favours sellers", tone: "neutral" },
      { when: "Low IV", meaning: "Calm expected — options cheap — favours buyers", tone: "neutral" },
    ],
    why: "IV drives option prices and risk. It also reveals fear: IV usually spikes when markets fall, so the *shape* of IV (skew) carries directional information.",
    analogy: "The insurance premium on a house — it rises when a storm looks likely.",
    example: "IV jumping before an event = market bracing for a large move.",
    level: "intermediate",
    category: "Volatility",
    hi: {
      short: "Market की उम्मीद कि price कितना move करेगी (options में shamil)।",
      what: "मौजूदा option prices से निकली volatility — ज़्यादा IV यानी महँगे options और बड़े expected swings.",
      how: "Option prices से back-solve करके। हम chain भर का ATM और OTM IV दिखाते हैं।",
      read: [
        { meaning: "बड़े moves की उम्मीद — options महँगे — sellers के पक्ष में" },
        { meaning: "शांति की उम्मीद — options सस्ते — buyers के पक्ष में" },
      ],
      why: "IV option prices और risk चलाता है। यह डर भी दिखाता है: market गिरने पर IV अक्सर उछलता है, इसलिए IV का *आकार* (skew) direction की जानकारी देता है।",
      analogy: "घर के बीमा का premium — तूफ़ान की आशंका होने पर बढ़ जाता है।",
      example: "किसी event से पहले IV का उछलना = market बड़े move के लिए तैयार।",
    },
  },
  iv_skew: {
    key: "iv_skew",
    title: "IV Skew",
    short: "Whether puts or calls carry richer IV — a fear/greed tell.",
    what: "The difference between out-of-the-money put IV and call IV.",
    how: "OTM put IV − OTM call IV. Positive = puts richer (Normal), negative = calls richer (Reverse), within ±2% = Flat.",
    read: [
      { when: "NORMAL (puts richer)", meaning: "Downside fear priced in — mild bearish", tone: "bearish" },
      { when: "FLAT", meaning: "Balanced — neutral", tone: "neutral" },
      { when: "REVERSE (calls richer)", meaning: "Upside chase / squeeze fear — mild bullish", tone: "bullish" },
    ],
    why: "Traders pay up for protection on the side they fear. Rich puts = the market is hedging downside (cautious); rich calls = chasing upside (often in rallies/squeezes).",
    analogy: "Which exit door people crowd toward tells you what they're afraid of.",
    example: "Puts 4% richer than calls = Normal skew = downside being hedged → mild bearish.",
    level: "advanced",
    category: "Volatility",
    hi: {
      short: "Puts या calls किसका IV ज़्यादा रिच है — fear/greed का संकेत.",
      what: "Out-of-the-money put IV और call IV का फ़र्क़।",
      how: "OTM put IV − OTM call IV. Positive = puts richer (Normal), negative = calls richer (Reverse), ±2% के अंदर = Flat.",
      read: [
        { meaning: "Downside का डर priced in — हल्का bearish" },
        { meaning: "Balanced — neutral" },
        { meaning: "Upside की दौड़ / squeeze का डर — हल्का bullish" },
      ],
      why: "Traders जिस side से डरते हैं उसकी protection के लिए ज़्यादा pay करते हैं। Rich puts = market downside hedge कर रहा (सतर्क); rich calls = upside के पीछे भाग रहा (अक्सर rally/squeeze में)।",
      analogy: "लोग जिस exit gate की तरफ़ भीड़ लगाते हैं वही बताता है कि वे किससे डरे हैं।",
      example: "Puts, calls से 4% richer = Normal skew = downside hedge हो रहा → हल्का bearish.",
    },
  },
  expected_range: {
    key: "expected_range",
    title: "Expected Range",
    short: "The band price is likely to stay within by expiry.",
    what: "A projected high–low range blending IV-implied move, OI walls and the ATM straddle.",
    how: "We combine an IV/√time estimate, the nearest OI walls, and the straddle move, then take a sensible blend.",
    read: [],
    why: "It frames realistic targets and stops, and tells you whether a strategy's strikes sit inside or outside the likely range.",
    analogy: "The weather forecast's high-low for the day.",
    example: "Expected 23,250–23,700 → fading moves near the edges, not chasing beyond them.",
    level: "intermediate",
    category: "Volatility",
    hi: {
      short: "वह band जिसमें expiry तक price के रहने की संभावना है।",
      what: "एक अनुमानित high–low range जो IV-implied move, OI walls और ATM straddle को मिलाती है।",
      how: "हम IV/√time का अनुमान, सबसे पास के OI walls, और straddle move को मिलाकर एक संतुलित blend लेते हैं।",
      why: "यह realistic targets और stops तय करती है, और बताती है कि किसी strategy के strikes likely range के अंदर हैं या बाहर।",
      analogy: "दिन के मौसम का high-low forecast.",
      example: "Expected 23,250–23,700 → किनारों के पास moves को fade करो, उनसे आगे मत भागो।",
    },
  },
  straddle_move: {
    key: "straddle_move",
    title: "Straddle-Implied Move (1σ)",
    short: "The market's own forecast of the move to expiry = ATM call + put price.",
    what: "The combined premium of the ATM call and put — the move size the market is pricing in (≈ 1 standard deviation).",
    how: "ATM call LTP + ATM put LTP. The 2σ band is twice that.",
    read: [],
    why: "It's the market's direct, real-money estimate of the expected move — usually more reliable than a textbook IV×√time calculation.",
    analogy: "Asking the bookmaker directly how big the swing will be, instead of estimating it yourself.",
    example: "ATM straddle = 175 → market expects ±175 points by expiry (≈68% chance within that band).",
    level: "intermediate",
    category: "Volatility",
    hi: {
      short: "Expiry तक move का market का अपना forecast = ATM call + put price.",
      what: "ATM call और put का मिला premium — वह move size जो market price कर रहा है (≈ 1 standard deviation)।",
      how: "ATM call LTP + ATM put LTP. 2σ band इसका दोगुना।",
      why: "यह expected move का market का सीधा, असली पैसे वाला अनुमान है — आमतौर पर किताबी IV×√time से ज़्यादा भरोसेमंद।",
      analogy: "ख़ुद अंदाज़ा लगाने की जगह bookmaker से सीधे पूछना कि swing कितना बड़ा होगा।",
      example: "ATM straddle = 175 → market expiry तक ±175 points की उम्मीद करता है (उस band में ≈68% chance)।",
    },
  },

  // ── Gamma ─────────────────────────────────────────────────────────────
  gex: {
    key: "gex",
    title: "GEX — Gamma Exposure",
    short: "Whether option dealers will dampen moves (calm) or amplify them (volatile).",
    what: "The net gamma that market-maker dealers hold across all strikes. It sets the day's 'personality'.",
    how: "Sum each strike's dealer gamma × OI. Positive total = dampening regime; negative = amplifying regime.",
    read: [
      { when: "POSITIVE GEX", meaning: "Dealers fade moves — price pinned / mean-reverting — ranges hold", tone: "neutral" },
      { when: "NEGATIVE GEX", meaning: "Dealers chase moves — trendy / volatile — breakouts run", tone: "neutral" },
    ],
    why: "To stay hedged, dealers must trade against (positive gamma) or with (negative gamma) the move. This mechanical flow is one of the most reliable drivers of whether a day chops or trends.",
    analogy: "Positive gamma = shock absorbers smoothing the ride; negative gamma = a skateboard that speeds up whichever way it tips.",
    example: "Negative GEX + a break of support → expect the drop to accelerate, not bounce.",
    level: "advanced",
    category: "Gamma",
    hi: {
      short: "Option dealers moves को दबाएँगे (शांत) या बढ़ाएँगे (volatile)।",
      what: "सभी strikes पर market-maker dealers का net gamma. यह दिन का 'स्वभाव' तय करता है।",
      how: "हर strike का dealer gamma × OI जोड़ो। Positive total = दबाने वाला regime; negative = बढ़ाने वाला regime.",
      read: [
        { meaning: "Dealers moves fade करते हैं — price pinned / mean-reverting — ranges टिकती हैं" },
        { meaning: "Dealers moves के पीछे भागते हैं — trendy / volatile — breakouts चलते हैं" },
      ],
      why: "Hedged रहने के लिए dealers को move के ख़िलाफ़ (positive gamma) या साथ (negative gamma) trade करना पड़ता है। यह mechanical flow सबसे भरोसेमंद कारणों में से है कि दिन chop करेगा या trend.",
      analogy: "Positive gamma = झटके सोखने वाले shock absorbers; negative gamma = skateboard जो जिधर झुके उधर और तेज़ हो जाए।",
      example: "Negative GEX + support का टूटना → गिरावट के तेज़ होने की उम्मीद करो, bounce की नहीं।",
    },
  },
  zero_gamma: {
    key: "zero_gamma",
    title: "Zero-Gamma Flip Level",
    short: "The price where the market flips between calm and volatile.",
    what: "The level at which net dealer gamma crosses zero — above it tends to be stable, below it volatile.",
    how: "We scan prices across the chain and find where net GEX changes sign.",
    read: [
      { when: "Spot ABOVE flip", meaning: "Positive-gamma / stabilised zone", tone: "neutral" },
      { when: "Spot BELOW flip", meaning: "Negative-gamma / volatile zone", tone: "bearish" },
    ],
    why: "It's a key intraday pivot: crossing it can flip the whole character of the tape from range-bound to trending.",
    analogy: "The waterline of a boat — above it you float calmly, below it you're underwater and things get wild.",
    example: "Flip at 23,400; spot 23,450 → just in the calm zone. A drop below 23,400 risks a volatility expansion.",
    level: "advanced",
    category: "Gamma",
    hi: {
      short: "वह price जहाँ market शांत और volatile के बीच पलटता है।",
      what: "वह level जहाँ net dealer gamma शून्य पार करता है — उसके ऊपर आमतौर पर stable, नीचे volatile.",
      how: "हम chain भर की prices scan करके वह जगह ढूँढते हैं जहाँ net GEX का sign बदलता है।",
      read: [
        { meaning: "Positive-gamma / stabilised zone" },
        { meaning: "Negative-gamma / volatile zone" },
      ],
      why: "यह एक key intraday pivot है: इसे पार करना पूरे tape का स्वभाव range-bound से trending में पलट सकता है।",
      analogy: "नाव की waterline — उसके ऊपर आप शांति से तैरते हैं, नीचे आप डूबे हुए हैं और हालात बेक़ाबू।",
      example: "Flip 23,400 पर; spot 23,450 → बस शांत zone में। 23,400 के नीचे गिरना volatility expansion का ख़तरा।",
    },
  },
  gamma_walls: {
    key: "gamma_walls",
    title: "Gamma Walls",
    short: "The strikes with the most dealer gamma — the strongest magnets and S/R.",
    what: "The call wall (resistance) and put wall (support) where dealer hedging is heaviest.",
    how: "Strikes with the largest call-gamma×OI (above spot) and put-gamma×OI (below spot).",
    read: [
      { when: "Call wall", meaning: "Strong resistance / upside magnet", tone: "bearish" },
      { when: "Put wall", meaning: "Strong support / downside magnet", tone: "bullish" },
    ],
    why: "Dealer hedging is most intense at these strikes, so price tends to stall or get pinned there — often more reliable than raw-OI levels.",
    analogy: "The strongest magnets on the fridge — the marble keeps getting drawn to them.",
    example: "Call wall 23,700 / put wall 23,250 → price likely boxed between them on a positive-gamma day.",
    level: "advanced",
    category: "Gamma",
    hi: {
      short: "सबसे ज़्यादा dealer gamma वाले strikes — सबसे मज़बूत magnets और S/R.",
      what: "Call wall (resistance) और put wall (support) जहाँ dealer hedging सबसे भारी है।",
      how: "सबसे बड़े call-gamma×OI (spot के ऊपर) और put-gamma×OI (spot के नीचे) वाले strikes.",
      read: [
        { meaning: "मज़बूत resistance / upside magnet" },
        { meaning: "मज़बूत support / downside magnet" },
      ],
      why: "इन strikes पर dealer hedging सबसे तेज़ होती है, इसलिए price वहाँ रुकती या pin होती है — अक्सर raw-OI levels से ज़्यादा भरोसेमंद।",
      analogy: "फ़्रिज पर सबसे मज़बूत चुम्बक — कंचा बार-बार उन्हीं की तरफ़ खिंचता है।",
      example: "Call wall 23,700 / put wall 23,250 → positive-gamma दिन पर price इन्हीं के बीच box रहने की संभावना।",
    },
  },

  // ── Greeks ────────────────────────────────────────────────────────────
  delta: {
    key: "delta",
    title: "Delta",
    short: "How much an option's price moves per 1 point move in the underlying.",
    what: "Sensitivity of the option price to the underlying; also a rough probability of expiring in-the-money.",
    how: "ATM ≈ 0.5; deep ITM → toward 1 (calls) / −1 (puts); far OTM → toward 0.",
    read: [],
    why: "Tells you how 'stock-like' an option is and how exposed your position is to direction.",
    analogy: "The gear ratio between the option and the index.",
    example: "Delta 0.5 → option gains ~₹0.50 for each 1-point rise in the index.",
    level: "advanced",
    category: "Greeks",
    hi: {
      short: "Underlying के 1 point move पर option की price कितनी हिलती है।",
      what: "Underlying के प्रति option price की sensitivity; साथ ही in-the-money expire होने की मोटी probability.",
      how: "ATM ≈ 0.5; deep ITM → 1 की ओर (calls) / −1 (puts); दूर OTM → 0 की ओर।",
      why: "बताता है कि option कितना 'stock जैसा' है और आपकी position direction के प्रति कितनी exposed है।",
      analogy: "Option और index के बीच का gear ratio.",
      example: "Delta 0.5 → index के हर 1-point बढ़ने पर option ~₹0.50 कमाता है।",
    },
  },
  gamma: {
    key: "gamma",
    title: "Gamma",
    short: "How fast delta itself changes — highest at ATM.",
    what: "The rate of change of delta as the underlying moves.",
    how: "Peaks for ATM options and near expiry; small for far OTM/ITM.",
    read: [],
    why: "High gamma means your directional exposure changes quickly — great when right, dangerous when wrong, and it's what powers the GEX/pinning effects.",
    analogy: "The accelerator's sensitivity — a small push creates a fast change.",
    example: "Near expiry, ATM gamma is huge, so price can whip around those strikes.",
    level: "advanced",
    category: "Greeks",
    hi: {
      short: "Delta ख़ुद कितनी तेज़ी से बदलता है — ATM पर सबसे ज़्यादा।",
      what: "Underlying के हिलने पर delta के बदलने की दर।",
      how: "ATM options और expiry के पास सबसे ज़्यादा; दूर OTM/ITM पर कम।",
      why: "ज़्यादा gamma यानी आपका directional exposure तेज़ी से बदलता है — सही होने पर बढ़िया, ग़लत होने पर ख़तरनाक, और यही GEX/pinning असर चलाता है।",
      analogy: "Accelerator की sensitivity — हल्का दबाव बड़ा बदलाव।",
      example: "Expiry के पास ATM gamma बहुत बड़ा होता है, इसलिए price उन strikes के आसपास whip कर सकती है।",
    },
  },
  theta: {
    key: "theta",
    title: "Theta",
    short: "How much value an option loses each day from time passing.",
    what: "Time decay — the daily erosion of an option's premium, all else equal.",
    how: "Accelerates as expiry approaches; worst for buyers in the final days.",
    read: [],
    why: "It's why the app blocks directional buying near expiry: even a correct view can lose if theta eats the premium first.",
    analogy: "An ice cube melting faster the closer you hold it to a flame (expiry).",
    example: "2 DTE: a bought option can lose most of its time value in a single day.",
    level: "advanced",
    category: "Greeks",
    hi: {
      short: "समय बीतने से option हर दिन कितनी value खोता है।",
      what: "Time decay — बाक़ी सब बराबर रहने पर option के premium का रोज़ का क्षरण।",
      how: "Expiry पास आते ही तेज़ होता है; आख़िरी दिनों में buyers के लिए सबसे बुरा।",
      why: "इसीलिए app expiry के पास directional buying रोकता है: सही view भी हार सकता है अगर theta पहले premium खा जाए।",
      analogy: "बर्फ़ का टुकड़ा जो आँच (expiry) के जितना पास, उतना तेज़ पिघले।",
      example: "2 DTE: खरीदा option एक ही दिन में अपनी ज़्यादातर time value खो सकता है।",
    },
  },
  vega: {
    key: "vega",
    title: "Vega",
    short: "How much an option's price changes when IV changes by 1%.",
    what: "Sensitivity of the option premium to implied volatility.",
    how: "Largest for ATM and longer-dated options.",
    read: [],
    why: "You can be right on direction but lose if IV collapses (a 'vol crush'), e.g. right after an event — vega explains that.",
    analogy: "How much the insurance premium swings when the storm forecast changes.",
    example: "Buy options into high IV, event passes, IV drops → vega losses even if price moved your way.",
    level: "advanced",
    category: "Greeks",
    hi: {
      short: "IV के 1% बदलने पर option की price कितनी बदलती है।",
      what: "Implied volatility के प्रति option premium की sensitivity.",
      how: "ATM और लंबी-expiry वाले options में सबसे ज़्यादा।",
      why: "आप direction पर सही हो सकते हैं पर IV गिरने ('vol crush') पर हार सकते हैं, जैसे किसी event के तुरंत बाद — vega यही समझाता है।",
      analogy: "तूफ़ान का forecast बदलने पर बीमा का premium कितना झूलता है।",
      example: "ऊँचे IV में options खरीदे, event बीता, IV गिरा → price आपके पक्ष में जाने पर भी vega का नुक़सान।",
    },
  },

  // ── Engine ────────────────────────────────────────────────────────────
  weighted_score: {
    key: "weighted_score",
    title: "Weighted Score & Probability",
    short: "All signals combined into one −100…+100 score, then into Bull/Bear/Sideways %.",
    what: "Each parameter scores −100 (bearish) to +100 (bullish); we weight and sum them into an overall bias.",
    how: "Score = Σ(parameter score × weight). The sign and size map to the three probability bars.",
    read: [
      { when: "Score > 0", meaning: "Net bullish tilt", tone: "bullish" },
      { when: "Score ≈ 0", meaning: "Sideways / unclear", tone: "neutral" },
      { when: "Score < 0", meaning: "Net bearish tilt", tone: "bearish" },
    ],
    why: "No single signal is reliable alone; blending many reduces noise and gives one at-a-glance read.",
    analogy: "A weighted average of many analysts' votes into one house view.",
    example: "Score +26 → ~60% bullish / 24% bearish / 16% sideways.",
    level: "intermediate",
    category: "Engine",
    hi: {
      short: "सारे signals मिलाकर एक −100…+100 score, फिर Bull/Bear/Sideways % में।",
      what: "हर parameter −100 (bearish) से +100 (bullish) तक score देता है; हम उन्हें weight देकर जोड़कर overall bias बनाते हैं।",
      how: "Score = Σ(parameter score × weight). Sign और size तीन probability bars में बदल जाते हैं।",
      read: [
        { meaning: "कुल मिलाकर bullish झुकाव" },
        { meaning: "Sideways / अस्पष्ट" },
        { meaning: "कुल मिलाकर bearish झुकाव" },
      ],
      why: "अकेला कोई signal भरोसेमंद नहीं; कई को मिलाने से noise घटता है और एक नज़र में पढ़ने लायक बनता है।",
      analogy: "कई analysts के votes का weighted average एक house view में।",
      example: "Score +26 → ~60% bullish / 24% bearish / 16% sideways.",
    },
  },
  confidence: {
    key: "confidence",
    title: "Confidence",
    short: "How strong the overall signal is (LOW / MODERATE / HIGH).",
    what: "A label based on the magnitude of the weighted score.",
    how: "|score| > 60 = HIGH, > 30 = MODERATE, else LOW.",
    read: [],
    why: "A 60% bullish read at LOW confidence is a weak edge; the same at HIGH confidence is far more actionable.",
    analogy: "A weather forecast's certainty: '60% rain, but we're not very sure' vs 'very sure'.",
    example: "Score +18 → bullish but LOW confidence → don't bet big.",
    level: "intermediate",
    category: "Engine",
    hi: {
      short: "Overall signal कितना मज़बूत है (LOW / MODERATE / HIGH)।",
      what: "Weighted score के आकार पर आधारित एक label.",
      how: "|score| > 60 = HIGH, > 30 = MODERATE, वरना LOW.",
      why: "LOW confidence पर 60% bullish कमज़ोर edge है; वही HIGH confidence पर कहीं ज़्यादा actionable.",
      analogy: "मौसम forecast की पक्की राय: '60% बारिश, पर हमें ज़्यादा यक़ीन नहीं' बनाम 'पूरा यक़ीन'.",
      example: "Score +18 → bullish पर LOW confidence → बड़ा दांव मत लगाओ।",
    },
  },
  alignment: {
    key: "alignment",
    title: "Signal Alignment / Conviction",
    short: "How many independent signals agree — agreement = conviction.",
    what: "Counts how many parameters point the same way, separate from the weighted score.",
    how: "Tally bullish vs bearish vs neutral signals; high agreement among many = HIGH conviction.",
    read: [
      { when: "Most signals agree", meaning: "High conviction — trustworthy bias", tone: "neutral" },
      { when: "Signals split", meaning: "Conflict — treat the headline with caution", tone: "neutral" },
    ],
    why: "A blended % can look decisive while the underlying signals actually disagree. Alignment exposes that, so you know when to trust the call.",
    analogy: "A jury: a unanimous verdict is far stronger than a split one, even if both 'convict'.",
    example: "Score says bullish, but 4 signals bullish and 4 bearish → conflict → low conviction.",
    level: "intermediate",
    category: "Engine",
    hi: {
      short: "कितने independent signals सहमत हैं — सहमति = conviction.",
      what: "गिनता है कि weighted score से अलग, कितने parameters एक ही तरफ़ इशारा करते हैं।",
      how: "Bullish बनाम bearish बनाम neutral signals गिनो; कई में ज़्यादा सहमति = HIGH conviction.",
      read: [
        { meaning: "ज़्यादातर signals सहमत — High conviction, भरोसेमंद bias" },
        { meaning: "Signals बँटे हुए — conflict, headline को सावधानी से लो" },
      ],
      why: "मिला हुआ % पक्का दिख सकता है जबकि नीचे के signals असल में असहमत हों। Alignment इसे उजागर करता है, ताकि पता चले कब call पर भरोसा करें।",
      analogy: "जूरी: सर्वसम्मत फ़ैसला बँटे हुए से कहीं मज़बूत, भले दोनों 'दोषी' कहें।",
      example: "Score bullish कहता है, पर 4 signals bullish और 4 bearish → conflict → low conviction.",
    },
  },
  track_record: {
    key: "track_record",
    title: "Prediction Track Record",
    short: "Real hit-rate — each call graded against the next snapshot's move.",
    what: "A running scorecard of how often the app's direction call was right on your own uploads.",
    how: "Each analysis is logged; when you upload the next snapshot, the previous call is graded UP/DOWN/FLAT vs the actual move.",
    read: [
      { when: "Hit-rate > 55%", meaning: "Edge holding up on your data", tone: "bullish" },
      { when: "Hit-rate < 45%", meaning: "Underperforming — don't over-trust it", tone: "bearish" },
    ],
    why: "The probability % is a heuristic, not a proven model. This measures how it actually performs so you trust numbers, not vibes.",
    analogy: "A weather app that keeps score of its own forecasts so you know how much to rely on it.",
    example: "Upload morning then afternoon snapshots over a week → a real hit-rate emerges.",
    level: "intermediate",
    category: "Engine",
    hi: {
      short: "असली hit-rate — हर call को अगले snapshot के move के ख़िलाफ़ जाँचा जाता है।",
      what: "एक चलता scorecard कि आपके अपने uploads पर app की direction call कितनी बार सही रही।",
      how: "हर analysis log होती है; अगला snapshot upload करते ही पिछली call को असली move के मुक़ाबले UP/DOWN/FLAT grade किया जाता है।",
      read: [
        { meaning: "आपके data पर edge टिक रहा है" },
        { meaning: "कमज़ोर प्रदर्शन — इस पर ज़्यादा भरोसा मत करो" },
      ],
      why: "Probability % एक heuristic है, सिद्ध model नहीं। यह नापता है कि असल में कैसा perform करता है, ताकि आप numbers पर भरोसा करें, अंदाज़े पर नहीं।",
      analogy: "एक मौसम app जो अपने ही forecasts का हिसाब रखे ताकि पता चले कितना भरोसा करें।",
      example: "एक हफ़्ते तक सुबह फिर दोपहर के snapshots upload करो → असली hit-rate उभर आता है।",
    },
  },
  resistance_support_ratio: {
    key: "resistance_support_ratio",
    title: "Resistance/Support Ratio",
    short: "Compares the strongest call wall vs the strongest put wall.",
    what: "Top call OI ÷ top put OI — which side's wall is heavier.",
    how: ">1.5 = ceiling stronger (bearish), <0.7 = floor stronger (bullish), between = balanced.",
    read: [
      { when: "> 1.5", meaning: "Resistance dominates — capped", tone: "bearish" },
      { when: "0.7–1.5", meaning: "Balanced", tone: "neutral" },
      { when: "< 0.7", meaning: "Support dominates — floor stronger", tone: "bullish" },
    ],
    why: "If the floor is much thicker than the ceiling (or vice-versa), price is more likely to break the weaker side.",
    analogy: "Tug-of-war — whichever team is heavier tends to win ground.",
    example: "Top put OI double the top call OI → ratio 0.5 → bullish floor.",
    level: "intermediate",
    category: "Engine",
    hi: {
      short: "सबसे मज़बूत call wall बनाम सबसे मज़बूत put wall की तुलना।",
      what: "Top call OI ÷ top put OI — किस side का wall भारी है।",
      how: ">1.5 = ceiling मज़बूत (bearish), <0.7 = floor मज़बूत (bullish), बीच में = balanced.",
      read: [
        { meaning: "Resistance हावी — capped" },
        { meaning: "Balanced" },
        { meaning: "Support हावी — floor मज़बूत" },
      ],
      why: "अगर floor, ceiling से बहुत मोटा हो (या उल्टा), तो price के कमज़ोर side को तोड़ने की संभावना ज़्यादा।",
      analogy: "रस्साकशी — जो टीम भारी होती है वही ज़मीन जीतती है।",
      example: "Top put OI, top call OI का दोगुना → ratio 0.5 → bullish floor.",
    },
  },
  dte_effect: {
    key: "dte_effect",
    title: "DTE Effect",
    short: "Adjusts the read as expiry nears (pinning up, buying down).",
    what: "A modifier that boosts Max Pain's pull and flags theta risk when few days remain.",
    how: "≤3 DTE doubles Max Pain weight and adds a sideways pull; 4–7 DTE boosts it 1.5×; >7 no change.",
    read: [],
    why: "Option mechanics change near expiry: pinning strengthens and time decay punishes buyers, so the same chain implies different action.",
    analogy: "The last lap of a race — the rules of engagement tighten.",
    example: "2 DTE → stronger pull to Max Pain and a 'NO TRADE' on directional buying.",
    level: "intermediate",
    category: "Engine",
    hi: {
      short: "Expiry पास आते ही read को adjust करता है (pinning ऊपर, buying नीचे)।",
      what: "एक modifier जो कम दिन बचने पर Max Pain का खिंचाव बढ़ाता है और theta risk का संकेत देता है।",
      how: "≤3 DTE पर Max Pain weight दोगुना और sideways pull जोड़ता है; 4–7 DTE पर 1.5×; >7 पर कोई बदलाव नहीं।",
      why: "Expiry के पास option mechanics बदलते हैं: pinning मज़बूत होती है और time decay buyers को सज़ा देता है, इसलिए वही chain अलग action दिखाती है।",
      analogy: "रेस का आख़िरी lap — खेल के नियम सख़्त हो जाते हैं।",
      example: "2 DTE → Max Pain की तरफ़ ज़्यादा खिंचाव और directional buying पर 'NO TRADE'.",
    },
  },

  // ── Strategy ──────────────────────────────────────────────────────────
  bull_call_spread: {
    key: "bull_call_spread",
    title: "Bull Call Spread",
    short: "A capped-cost bullish bet: buy a call, sell a higher call.",
    what: "Buy an ATM call and sell a higher-strike call to lower the cost — profits if price rises moderately.",
    how: "Buy ATM call, sell call near resistance. Max profit at/above the sold strike; max loss = net premium paid.",
    read: [],
    why: "Cheaper and lower-risk than buying a naked call; ideal when you're bullish but want defined risk.",
    analogy: "Betting on a horse but capping both your stake and your winnings.",
    example: "Buy 23,450 CE, sell 23,700 CE → profit if NIFTY drifts up toward 23,700.",
    level: "intermediate",
    category: "Strategy",
    hi: {
      short: "सीमित-लागत वाला bullish दांव: एक call खरीदो, ऊँची call बेचो।",
      what: "ATM call खरीदो और ऊँचे strike की call बेचकर लागत घटाओ — price हल्का ऊपर जाने पर मुनाफ़ा।",
      how: "ATM call खरीदो, resistance के पास call बेचो। Max profit बेचे strike पर/उसके ऊपर; max loss = चुकाया net premium.",
      why: "नंगी call खरीदने से सस्ता और कम-risk; तब बढ़िया जब आप bullish हो पर defined risk चाहो।",
      analogy: "घोड़े पर दांव, पर अपना दांव और जीत दोनों सीमित करके।",
      example: "23,450 CE खरीदो, 23,700 CE बेचो → NIFTY 23,700 की तरफ़ बढ़े तो मुनाफ़ा।",
    },
  },
  bear_put_spread: {
    key: "bear_put_spread",
    title: "Bear Put Spread",
    short: "A capped-cost bearish bet: buy a put, sell a lower put.",
    what: "Buy an ATM put and sell a lower-strike put — profits if price falls moderately.",
    how: "Buy ATM put, sell put near support. Max profit at/below the sold strike; max loss = net premium paid.",
    read: [],
    why: "Defined-risk way to play a downside view without the high cost/decay of a naked put.",
    analogy: "A bet on rain, with both your cost and payout capped.",
    example: "Buy 23,450 PE, sell 23,250 PE → profit if NIFTY slips toward 23,250.",
    level: "intermediate",
    category: "Strategy",
    hi: {
      short: "सीमित-लागत वाला bearish दांव: एक put खरीदो, नीची put बेचो।",
      what: "ATM put खरीदो और नीचे strike की put बेचो — price हल्का नीचे जाने पर मुनाफ़ा।",
      how: "ATM put खरीदो, support के पास put बेचो। Max profit बेचे strike पर/उसके नीचे; max loss = चुकाया net premium.",
      why: "नंगी put की ऊँची लागत/decay बिना downside view खेलने का defined-risk तरीक़ा।",
      analogy: "बारिश पर दांव, जिसमें लागत और payout दोनों सीमित।",
      example: "23,450 PE खरीदो, 23,250 PE बेचो → NIFTY 23,250 की तरफ़ फिसले तो मुनाफ़ा।",
    },
  },
  iron_condor: {
    key: "iron_condor",
    title: "Iron Condor",
    short: "A range-bound bet: collect premium while price stays between the walls.",
    what: "Sell a call spread above and a put spread below — you keep the credit if price stays in the middle.",
    how: "Sell call near resistance & put near support, buy wings 300 pts out. Profit if price expires between the sold strikes.",
    read: [],
    why: "The go-to when you expect a quiet, range-bound market (often positive-gamma / high-IV) — time decay works for you.",
    analogy: "Being the casino: you profit as long as price doesn't stray too far either way.",
    example: "Sell 23,700 CE & 23,250 PE (buy 24,000/22,950 wings) → keep the credit if price stays in 23,250–23,700.",
    level: "advanced",
    category: "Strategy",
    hi: {
      short: "Range-bound दांव: price walls के बीच रहे तो premium कमाओ।",
      what: "ऊपर call spread और नीचे put spread बेचो — price बीच में रहे तो credit आपका।",
      how: "Resistance के पास call और support के पास put बेचो, 300 pts बाहर wings खरीदो। Price बेचे strikes के बीच expire हो तो मुनाफ़ा।",
      why: "तब चुनो जब शांत, range-bound market की उम्मीद हो (अक्सर positive-gamma / high-IV) — time decay आपके पक्ष में।",
      analogy: "ख़ुद casino बनना: जब तक price किसी तरफ़ बहुत दूर न जाए, आप कमाते हैं।",
      example: "23,700 CE और 23,250 PE बेचो (24,000/22,950 wings खरीदो) → price 23,250–23,700 में रहे तो credit रखो।",
    },
  },
  break_even: {
    key: "break_even",
    title: "Break-Even / Max Profit / Max Loss",
    short: "The price where a trade turns profitable, and its best/worst outcomes.",
    what: "Break-even = price at which P&L is zero. Max profit/loss = the capped best and worst results.",
    how: "Derived from the strikes and premiums of the strategy's legs.",
    read: [],
    why: "Knowing these up front tells you the risk/reward before you trade — non-negotiable for disciplined trading.",
    analogy: "Reading the odds and the maximum stake before placing a bet.",
    example: "Bull call spread: break-even 23,500, max profit ₹15,000, max loss ₹3,750.",
    level: "intermediate",
    category: "Strategy",
    hi: {
      short: "वह price जहाँ trade मुनाफ़े में आता है, और उसके best/worst नतीजे।",
      what: "Break-even = वह price जहाँ P&L शून्य हो। Max profit/loss = सीमित best और worst नतीजे।",
      how: "Strategy के legs के strikes और premiums से निकाला जाता है।",
      why: "इन्हें पहले से जानना trade से पहले risk/reward बता देता है — अनुशासित trading के लिए ज़रूरी।",
      analogy: "दांव लगाने से पहले odds और अधिकतम stake पढ़ना।",
      example: "Bull call spread: break-even 23,500, max profit ₹15,000, max loss ₹3,750.",
    },
  },
};

// Steps for the "How this app predicts" walkthrough.
export const HOW_IT_WORKS = [
  {
    title: "1. Read the raw chain",
    body: "We parse the NSE option-chain CSV into clean per-strike data: OI, change in OI, volume, IV and prices for every call and put.",
    keys: ["oi", "volume", "iv", "ltp"],
    hi: {
      title: "1. कच्ची chain पढ़ो",
      body: "हम NSE option-chain CSV को साफ़ per-strike data में बदलते हैं: हर call और put का OI, change in OI, volume, IV और prices.",
    },
  },
  {
    title: "2. Gauge sentiment",
    body: "PCR, Max Pain and the battlefield strike summarise what the crowd and the option writers expect.",
    keys: ["pcr", "max_pain", "battlefield"],
    hi: {
      title: "2. Sentiment नापो",
      body: "PCR, Max Pain और battlefield strike बताते हैं कि भीड़ और option writers क्या उम्मीद कर रहे हैं।",
    },
  },
  {
    title: "3. Find the levels",
    body: "Heavy call OI above = resistance; heavy put OI below = support. We weight these by fresh OI change and cluster them into zones.",
    keys: ["resistance", "support", "sr_zones"],
    hi: {
      title: "3. Levels ढूँढो",
      body: "ऊपर भारी call OI = resistance; नीचे भारी put OI = support. इन्हें fresh OI change से weight देकर zones में cluster करते हैं।",
    },
  },
  {
    title: "4. Read volatility & gamma",
    body: "IV skew shows fear/greed; the straddle gives the expected move; GEX tells us whether dealers will calm or amplify the day, with a flip level and gamma walls.",
    keys: ["iv_skew", "straddle_move", "gex", "zero_gamma", "gamma_walls"],
    hi: {
      title: "4. Volatility और gamma पढ़ो",
      body: "IV skew fear/greed दिखाता है; straddle expected move देता है; GEX बताता है कि dealers दिन को शांत करेंगे या बढ़ाएँगे, साथ में flip level और gamma walls.",
    },
  },
  {
    title: "5. Score the bias",
    body: "Each signal is scored −100…+100 and weighted into one number, then turned into Bullish / Bearish / Sideways percentages with a confidence label.",
    keys: ["weighted_score", "confidence"],
    hi: {
      title: "5. Bias को score दो",
      body: "हर signal को −100…+100 score देकर weight करके एक number बनता है, फिर Bullish / Bearish / Sideways percentages और confidence label में बदलता है।",
    },
  },
  {
    title: "6. Check agreement",
    body: "The alignment meter counts how many independent signals actually agree — high agreement means high conviction, a split means caution.",
    keys: ["alignment"],
    hi: {
      title: "6. सहमति जाँचो",
      body: "Alignment meter गिनता है कि कितने independent signals सच में सहमत हैं — ज़्यादा सहमति = high conviction, बँटवारा = सावधानी।",
    },
  },
  {
    title: "7. Suggest a strategy",
    body: "Based on the bias, days to expiry and the levels, we propose a defined-risk strategy (or 'NO TRADE') with break-even and max profit/loss.",
    keys: ["bull_call_spread", "bear_put_spread", "iron_condor", "break_even"],
    hi: {
      title: "7. Strategy सुझाओ",
      body: "Bias, days to expiry और levels के आधार पर हम एक defined-risk strategy (या 'NO TRADE') सुझाते हैं, break-even और max profit/loss के साथ।",
    },
  },
  {
    title: "8. Keep score",
    body: "Every call is logged and graded against your next snapshot, so you get a real hit-rate instead of trusting the numbers blindly.",
    keys: ["track_record"],
    hi: {
      title: "8. हिसाब रखो",
      body: "हर call log होती है और आपके अगले snapshot के ख़िलाफ़ grade होती है, ताकि आँख मूँदकर numbers पर भरोसा करने की जगह असली hit-rate मिले।",
    },
  },
];

// "How to read this" content for each chart, bilingual.
export const CHART_GUIDES = {
  oi: {
    title: "Open Interest chart",
    en: {
      howTo: [
        "X-axis = strike prices; Y-axis = OI in lakhs (L).",
        "RED bars = CALL OI (the resistance / ceiling side, above price).",
        "GREEN bars = PUT OI (the support / floor side, below price).",
        "The tallest red bar = strongest resistance; the tallest green bar = strongest support.",
        "The dashed yellow line marks the ATM strike (closest to spot).",
      ],
      example:
        "If the biggest red bar is at 23,700 and the biggest green at 23,250, the market is likely boxed between 23,250 (support) and 23,700 (resistance).",
    },
    hi: {
      howTo: [
        "X-axis = strike prices; Y-axis = OI lakhs (L) में।",
        "लाल bars = CALL OI (resistance / ceiling side, price के ऊपर)।",
        "हरी bars = PUT OI (support / floor side, price के नीचे)।",
        "सबसे ऊँची लाल bar = सबसे मज़बूत resistance; सबसे ऊँची हरी bar = सबसे मज़बूत support.",
        "पीली dashed लाइन ATM strike दिखाती है (spot के सबसे पास)।",
      ],
      example:
        "अगर सबसे बड़ी लाल bar 23,700 पर और सबसे बड़ी हरी 23,250 पर है, तो market के 23,250 (support) और 23,700 (resistance) के बीच box रहने की संभावना है।",
    },
  },
  gex: {
    title: "Gamma Exposure chart",
    en: {
      howTo: [
        "Each bar = net dealer gamma at that strike (green = positive, red = negative).",
        "POSITIVE total (green regime) = dealers calm the market → price gets pinned, ranges hold.",
        "NEGATIVE total (red regime) = dealers amplify moves → trends and breakouts run.",
        "The yellow dashed 'Flip' line is where the regime changes; the blue 'Spot' line is now.",
        "Call Wall = resistance magnet, Put Wall = support magnet (cards above the chart).",
      ],
      example:
        "Spot above the Flip with green bars → expect a calm, range-bound day pinned between the put and call walls. Break below the Flip → volatility can expand.",
    },
    hi: {
      howTo: [
        "हर bar = उस strike पर net dealer gamma (हरा = positive, लाल = negative)।",
        "POSITIVE total (हरा regime) = dealers market को शांत करते हैं → price pin होती है, ranges टिकती हैं।",
        "NEGATIVE total (लाल regime) = dealers moves बढ़ाते हैं → trends और breakouts चलते हैं।",
        "पीली dashed 'Flip' लाइन वहाँ है जहाँ regime बदलता है; नीली 'Spot' लाइन अभी की जगह।",
        "Call Wall = resistance magnet, Put Wall = support magnet (chart के ऊपर cards में)।",
      ],
      example:
        "Spot, Flip के ऊपर और हरी bars → शांत, range-bound दिन की उम्मीद, put और call walls के बीच pinned. Flip के नीचे टूटा → volatility बढ़ सकती है।",
    },
  },
  iv: {
    title: "IV Skew chart",
    en: {
      howTo: [
        "X-axis = strikes; Y-axis = implied volatility (%).",
        "The blue line is CALL IV, the orange line is PUT IV.",
        "Puts higher than calls (NORMAL skew) = downside fear is being hedged → mildly bearish.",
        "Calls higher than puts (REVERSE skew) = upside is being chased → mildly bullish.",
        "Lines close together (FLAT) = balanced, no strong fear either way.",
      ],
      example:
        "If the orange (PUT) line sits well above the blue (CALL) line, traders are paying up for downside protection — caution on longs.",
    },
    hi: {
      howTo: [
        "X-axis = strikes; Y-axis = implied volatility (%)।",
        "नीली लाइन CALL IV, नारंगी लाइन PUT IV।",
        "Puts, calls से ऊँचे (NORMAL skew) = downside का डर hedge हो रहा → हल्का bearish.",
        "Calls, puts से ऊँचे (REVERSE skew) = upside के पीछे दौड़ → हल्का bullish.",
        "लाइनें पास-पास (FLAT) = balanced, किसी तरफ़ ख़ास डर नहीं।",
      ],
      example:
        "अगर नारंगी (PUT) लाइन नीली (CALL) लाइन से काफ़ी ऊपर है, तो traders downside protection के लिए ज़्यादा pay कर रहे हैं — longs पर सावधानी।",
    },
  },
  range: {
    title: "Expected Range chart",
    en: {
      howTo: [
        "The colored band is where price is likely to stay by expiry.",
        "The blue pin (SPOT) is the current price; the yellow pin (MP) is Max Pain.",
        "Boxes below show four estimates: IV-based, OI-based, Straddle 1σ and the blended Expected.",
        "If spot sits below Max Pain, there's a mild upward pull toward it (and vice-versa).",
      ],
      example:
        "Expected 23,250–23,700 with spot at 23,450 → trade inside the band: buy near support, sell near resistance, don't chase breakouts unless a wall breaks.",
    },
    hi: {
      howTo: [
        "रंगीन band वह है जहाँ expiry तक price के रहने की संभावना है।",
        "नीला pin (SPOT) current price; पीला pin (MP) Max Pain।",
        "नीचे के boxes चार अनुमान दिखाते हैं: IV-based, OI-based, Straddle 1σ और मिला हुआ Expected.",
        "अगर spot, Max Pain के नीचे है तो उसकी तरफ़ हल्का ऊपर का खिंचाव (और उल्टा भी)।",
      ],
      example:
        "Expected 23,250–23,700, spot 23,450 → band के अंदर trade करो: support के पास खरीदो, resistance के पास बेचो, जब तक कोई wall न टूटे breakout के पीछे मत भागो।",
    },
  },
};

export function getEntry(key) {
  return GLOSSARY[key] || null;
}

// Resolve an entry's teaching fields for the active language.
// Falls back to English for any field missing a Hindi translation.
export function localize(entry, lang) {
  if (!entry || lang !== "hi" || !entry.hi) return entry;
  const hi = entry.hi;
  const merged = { ...entry };
  for (const f of ["short", "what", "how", "why", "analogy", "example"]) {
    if (hi[f]) merged[f] = hi[f];
  }
  if (Array.isArray(hi.read) && Array.isArray(entry.read)) {
    merged.read = entry.read.map((r, i) => ({
      ...r,
      meaning: hi.read[i]?.meaning || r.meaning,
    }));
  }
  return merged;
}

// Resolve a "How it works" step for the active language.
export function localizeStep(step, lang) {
  if (!step || lang !== "hi" || !step.hi) return step;
  return { ...step, title: step.hi.title || step.title, body: step.hi.body || step.body };
}

// Resolve a chart guide for the active language.
export function chartGuide(key, lang) {
  const g = CHART_GUIDES[key];
  if (!g) return null;
  const loc = lang === "hi" && g.hi ? g.hi : g.en;
  return { title: g.title, ...loc };
}
